tunnel: 8535390b-7b23-462a-a0a9-ed59a11120e4
credentials-file: /home/minipc/.cloudflared/8535390b-7b23-462a-a0a9-ed59a11120e4.json

ingress:
  # Minichat Frontend
  - hostname: chat.clubfivem.com
    service: http://localhost:3000
  
  # Minichat Backend API
  - hostname: api.clubfivem.com
    service: http://localhost:5000
  
  # POS System service
  - hostname: pos.clubfivem.com
    service: http://localhost:8080
  
  # Catch-all rule (required)
  - service: http_status:404
